### PR TITLE
Reworked EstimatorSelectionHelper

### PR DESCRIPTION
**Pull request by wdsrocha**
* fit method now accepts GridSearchCV keyword arguments
* score_summary method works a bit differently:
    - still concatenates all the cv_results_
    - only adds "estimator" column
    - all _single_ parameter rows were removed (reducing drastically the amount of NaN elements in the table)
    - shows proper row indexes
* minor changes and bug fixes

### CODE REVIEW

**Comment by davidsbatista** [comment]
Hello Wesley,

thanks for the input! Unfortunately somehow I was not notified by mail about this PR :( Have to review my github settings, I will merge it.

**Comment by doubianimehdi** [comment]
Hi, 

Somehow I can't get jaccard_score to appear in the dataframe out of the score_summary procedure, do you know how to achieve that ?
 thank you !

**Comment by davidsbatista** [comment]
I currrently lack the time to do this, but if you feel like it, open a PR.

**Comment by wdsrocha** [comment]
Hmm, strange. I'll take a look tonight.

**Comment by wdsrocha** [comment]
@doubianimehdi if you call the fit method like

`helper1.fit(X_cancer, y_cancer, scoring='jaccard', n_jobs=2)`

the jaccard scoring will be the selected method, so any column on the dataframe with the suffix `_score` will actually be referencing the jaccard score.

Does that addresses your issue or I have misunderstood the question?

**Comment by doubianimehdi** [comment]
@wdsrocha No you are right ! I've struggled to have my custom avg_jaccard score to display because I had to use make_scorers method , everything is fine , thanks for your answer !

**Pull request merged**
